
import process from 'node:process';

export default {
    // COOKIES NAMES
    REFRESH_TOKEN_COOKIE_NAME: process.env.REFRESH_TOKEN_COOKIE_NAME,
    // ALL COOKIES SECRET
    COOKIE_PARSER_SECRET: process.env.COOKIE_PARSER_SECRET,
    COOKIE_ENCRYPTED_SECRET: process.env.COOKIE_ENCRYPTED_SECRET,
    // ALL COOKIES CONFIG
    REFRESH_TOKEN_COOKIE_EXP: parseInt(process.env.REFRESH_TOKEN_COOKIE_EXP),
    // ALL JWT SECRET
    SECRET_KEY: process.env.SECRET_KEY,
    ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
    CALLBACK_TOKEN_SECRET: process.env.CALLBACK_TOKEN_SECRET,
    VERIFY_ACCOUNT_TOKEN_SECRET: process.env.VERIFY_ACCOUNT_TOKEN_SECRET,
    CREATE_ORG_TOKEN_SECRET: process.env.CREATE_ORG_TOKEN_SECRET,
    SIGN_UP_TOKEN_SECRET: process.env.SIGN_UP_TOKEN_SECRET,
    RESET_PASSWORD_TOKEN_SECRET: process.env.RESET_PASSWORD_TOKEN_SECRET,
    ACCEPT_OR_DECLINE_TOKEN_SECRET: process.env.ACCEPT_OR_DECLINE_TOKEN_SECRET,
    INVITATION_TOKEN_SECRET: process.env.INVITATION_TOKEN_SECRET,
    EXTERNAL_GUEST_TOKEN_SECRET: process.env.EXTERNAL_GUEST_TOKEN_SECRET,
    // ALL JWT EXP TIME
    ACCESS_TOKEN_EXP: process.env.ACCESS_TOKEN_EXP ,
    REFRESH_TOKEN_EXP: process.env.REFRESH_TOKEN_EXP ,
    CALLBACK_TOKEN_EXP: process.env.CALLBACK_TOKEN_EXP ,
    VERIFY_ACCOUNT_TOKEN_EXP: process.env.VERIFY_ACCOUNT_TOKEN_EXP ,
    CREATE_ORG_TOKEN_EXP: process.env.CREATE_ORG_TOKEN_EXP ,
    SIGN_UP_TOKEN_EXP: process.env.SIGN_UP_TOKEN_EXP,
    RESET_PASSWORD_TOKEN_EXP: process.env.RESET_PASSWORD_TOKEN_EXP,
    ACCEPT_OR_DECLINE_TOKEN_EXP: process.env.ACCEPT_OR_DECLINE_TOKEN_EXP,
    INVITATION_TOKEN_EXP: process.env.INVITATION_TOKEN_EXP,
    EXTERNAL_GUEST_TOKEN_EXP: process.env.EXTERNAL_GUEST_TOKEN_EXP,
    REDIRECT_URL_FRONT: process.env.REDIRECT_URL_FRONT,
    
    IS_PRODUCTION: ['production', 'staging'].indexOf(process.env.STATUS) >= 0,
    
    };